### ISSUE TITLE
请教：decode 结果跟服务器不一致

### ISSUE THREAD

**Issue by slightun** [zhangshiqian1214/sprotojs#11]
刚接触 skynet，服务器修改 simplewebsocket.lua 发送 wsplayer 结构：

    function handle.message(id, msg)
        --websocket.write(id, msg)
        local sprotoobj = sprotoloader.load(3)
        local msg_player = **sprotoobj:encode**("wsplayer", {name="player1", age=18})
        websocket.write(id, msg_player)
    end

wsplayer 定义为：
proto.struct = sprotoparser.parse [[
.wsplayer {
	name 0 : string
	age 1 : integer
}

在测试脚本中，使用 decode 解码
ws.onmessage = function (event) {
  console.log("[test_ws] onmessage=" + event.data);

  let decode_res = struct_sproto.**decode**("wsplayer", event.data)
  console.log("[test_ws] decode_res=" + decode_res.name, decode_res.age);
}
结果： name 和 age 解析后返回了 undefined
断点 function sproto_decode(st, data, size, cb, ud)  这个函数时，fn = toword(stream); 这行执行后 fn 是 0。

不确定什么原因呢？？求助~~

**Comment by zhangshiqian1214** [comment]
信息不够，看不出哪里的问题

**Comment by slightun** [comment]
我的错。。websocket.write(id, msg_player, "binary") 加 binary 参数就行了。

**Comment by slightun** [comment]
另外 rpc 可以正常使用么？还没尝试

**Comment by slightun** [comment]
感谢。刚测了下，RPC 发送和接收数据也正常。
