### ISSUE TITLE
微信小游戏超级慢了

### ISSUE THREAD

**Issue by xiaotiekeng** [zhangshiqian1214/sprotojs#16]
一个14K的文件,win上加载50MS,但是在微信小游戏上加载要7秒..天呀..~!你把ZIPZIP要解压一下~谢谢帮忙看下
[sproto.zip](https://github.com/zhangshiqian1214/sproto-js/files/11139810/sproto.zip)

**Comment by xiaotiekeng** [comment]
更新最新的库解决了...调到深夜...

**Comment by xiaotiekeng** [comment]
更新最新的库解决了...调到深夜...

**Comment by xiaotiekeng** [comment]
其实是加载二进制Bin文件的时候,要用new Unit8模式,,我用了那个自带的函数,会导致6秒,而用了Uint8直接是30毫秒

**Comment by zhangshiqian1214** [comment]
哦，学到了，我们主要用cocos creator做客户端，加载二进制也是用的cocos creator的加载方法，然后取出二进制数据给sproto.js，至于微信小游戏和浏览器的差距，我不太清楚，我主要做服务器开发
