### ISSUE TITLE
是否支持加载原文件（不用dump的.proto文件）？

### ISSUE THREAD

**Issue by tuyazuo** [zhangshiqian1214/sprotojs#2]
请教一下是否支持加载sproto原文件？
还有我使用creator测试，无论使用原文件还是二进制文件都没法正常运行
（在creator里我使用cc.loader.loadResDir加载或是使用jsb.fileUtils.getDataFromFile均不正常）
createNew之后得到的object  type_n始终是0，请问createNew需要传入的是什么类型的参数

**Comment by zhangshiqian1214** [comment]
很遗憾，加载原sproto文件用到了lua lpeg库, 你的用法不对，cc.loader.load 不支持二进制，但可以支持text格式load, 另外如果你觉得没什么麻烦，可以把spb再用base64.encode一下，然后在creator可以用 cc.loader.load, 然后base64.decode， 然后再传给sproto.createNew, 我就是这么用的，如果想放在服务器也行, http获取

**Comment by tuyazuo** [comment]
多谢，按照你提供的方法使用base64转换 测试成功了，就是有点小麻烦啊！

**Comment by zhangshiqian1214** [comment]
要么布置一个http服务器，就不用base64, 其实也就这两下，虽然转了一下，谁叫creator没有提供二进制读取呢
