### ISSUE TITLE
这里未初始为0

### ISSUE THREAD

**Issue by samoyedsun** [zhangshiqian1214/sprotojs#4]
未初始化就是未定义，未定义的值与数字比较永远为false,导致二分查找查不到！https://github.com/zhangshiqian1214/sproto-js/blob/454e53944cf78ed6aeab992ed1a8282b0d962ba0/sproto.js#L406

**Comment by TD1900** [comment]
空值与数字比较永远为false,导致二分查找查不到

**Comment by zhangshiqian1214** [comment]
已fix， thanks
