### ISSUE TITLE
当字段为负数时这里会导致编码后的结果不对

### ISSUE THREAD

**Issue by samoyedsun** [zhangshiqian1214/sprotojs#6]
改为vh = v;就没问题了

https://github.com/zhangshiqian1214/sproto-js/blob/153516b4cb72dbf1a88778d1b6ed3e489190029e/sproto.js#L1176

**Comment by zhangshiqian1214** [comment]
由于javascript的数字类型是64位的双精数，做位操作后，会截成32位的有符号整数，已经fix
