### ISSUE TITLE
关于sproto的packing疑问

### ISSUE THREAD

**Issue by lindxmooc** [zhangshiqian1214/sprotojs#7]
大神，能讲下，sproto是如何打包的吗，我看了云风的sproto介绍，发现讲的有点深奥，不是很理解，特别是对第一个字节 0xff 的情况，而且给的例子也不是很多。

**Comment by zhangshiqian1214** [comment]
我也很难讲的明白，你要拿到算法去试，对照云风的blog才会理解

**Comment by lindxmooc** [comment]
大神，那你创有什么交流群之类的吗，我想加个好友，向你探讨学习下

**Comment by zhangshiqian1214** [comment]
我没有创什么技术交流群，你可以到skynet的官方交流群里，里面有很多人都会解答问题的

**Comment by lindxmooc** [comment]
你说的是340504014，这个吗，我之前加了，发现都是在聊其他的，我提问，就立马被其他无关的消息给刷没了，没发现有哪个交流群是真正谈技术交流的

**Comment by zhangshiqian1214** [comment]
一般要看人家谈技术更多的会去github的issues或者看人家提交的代码记录，实在不会的也可以到群里面提问，有时会回答，我技术还很菜，只能在后面默默的学习了
