### ISSUE TITLE
二进制使用经常会报错，不是100%，估计是某种特殊情况引起的

### ISSUE THREAD

**Issue by BlueLeaf-HPY** [zhangshiqian1214/sprotojs#9]
你好，使用二进制过程中出现了下面的问题
![image](https://user-images.githubusercontent.com/27042820/55278339-d3a27900-5345-11e9-8916-9b41dff3b04e.png)
如图，代码是utils.js中的，我没有修改过，数组访问越界了，对应的协议如下
![image](https://user-images.githubusercontent.com/27042820/55278372-6d6a2600-5346-11e9-8a47-063cd477d609.png)
在解析key时，很大概率触发上面的越界问题

**Comment by zhangshiqian1214** [comment]
> 你好，使用二进制过程中出现了下面的问题
> ![image](https://user-images.githubusercontent.com/27042820/55278339-d3a27900-5345-11e9-8916-9b41dff3b04e.png)
> 如图，代码是utils.js中的，我没有修改过，数组访问越界了，对应的协议如下
> ![image](https://user-images.githubusercontent.com/27042820/55278372-6d6a2600-5346-11e9-8a47-063cd477d609.png)
> 在解析key时，很大概率触发上面的越界问题

tks, 这个地方确实被疏忽了，由于这里是二进制解析，不能同string一样处理，要特别处理一下，encode和decode处都使用Array传二进制数据就可以了, 我修改了一下，你试试看
